version: '3.6'

networks:
  default:
    name: interrogative

services:
  manager:
    image: interrogative-manager:latest
    container_name: interrogative-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - 1311:1311
