version: '3.6'

networks:
  interrogative:
    name: interrogative
  interrogative-db:
    name: interrogative-db

services:
  manager:
    image: interrogative-manager:latest
    container_name: interrogative-manager
    networks:
      - interrogative
      - interrogative-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - 1311:1311
    depends_on:
      - mongo
  messanger:
    image: interrogative-messanger:latest
    container_name: interrogative-messanger
    networks:
      - interrogative-db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - 25:25
       - 587:587
    depends_on:
      - mongo
  mongo:
    image: interrogative-mongo:latest
    container_name: interrogative-mongo
    networks:
      - interrogative-db
    volumes:
      - interrogative-data:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  interrogative-data:
    name: interrogative-data
