version: '3.6'

networks:
  interrogative:
    name: interrogative
  interrogative-db:
    name: interrogative-db

services:
  manager:
    image: interrogative-manager:latest
    container_name: interrogative-manager
    networks:
      - interrogative
      - interrogative-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 0.0.0.0:1311:1311
    environment:
      - INTERROGATIVE_ADMIN_EMAIL
      - INTERROGATIVE_ADMIN_PASSWORD
      - INTERROGATIVE_AUTO_REMOVE
    depends_on:
      - mongo
  messenger:
    image: interrogative-messenger:latest
    container_name: interrogative-messenger
    networks:
      - interrogative-db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 0.0.0.0:25:25
      - 0.0.0.0:587:587
    environment:
      - INTERROGATIVE_MAIL_HOST
      - INTERROGATIVE_MAIL_PORT
      - INTERROGATIVE_MAIL_USER
      - INTERROGATIVE_MAIL_PASSWORD
    depends_on:
      - mongo
  mongo:
    image: interrogative-mongo:latest
    container_name: interrogative-mongo
    networks:
      - interrogative-db
    volumes:
      - interrogative-data:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  interrogative-data:
    name: interrogative-data
